export const SIGNUP_STARTED = "SIGNUP_STARTED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const CHECK_SIGNUP_STARTED = "CHECK_SIGNUP_STARTED";
export const CHECK_SIGNUP_SUCCESS = "CHECK_SIGNUP_SUCCESS";
export const CHECK_SIGNUP_FAILED = "CHECK_SIGNUP_FAILED";

export const PATIENT_REGISTER_STARTED = "PATIENT_REGISTER_STARTED";
export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAILED = "PATIENT_REGISTER_FAILED";

export const GET_PATIENT_INFO_STARTED = "GET_PATIENT_INFO_STARTED";
export const GET_PATIENT_INFO_SUCCESS = "GET_PATIENT_INFO_SUCCESS";
export const GET_PATIENT_INFO_FAILED = "GET_PATIENT_INFO_FAILED";

export const UPDATE_PATIENT_STARTED = "UPDATE_PATIENT_STARTED";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED";

export const ON_CHANGE_UPDATE = "ON_CHANGE_UPDATE";

export const DELETE_PATIENT_STARTED = "DELETE_PATIENT_STARTED";
export const DELTE_PATIENT_SUCCESS = "DELTE_PATIENT_SUCCESS";
export const DELTE_PATIENT_FAILED = "DELTE_PATIENT_FAILED";
