export const SIGNUP_STARTED = "SIGNUP_STARTED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const CHECK_SIGNUP_STARTED = "CHECK_SIGNUP_STARTED";
export const CHECK_SIGNUP_SUCCESS = "CHECK_SIGNUP_SUCCESS";
export const CHECK_SIGNUP_FAILED = "CHECK_SIGNUP_FAILED";

export const PATIENT_REGISTER_STARTED = "PATIENT_REGISTER_STARTED";
